# vim ft=yaml
language: erlang
cache:
 - apt
env:
 matrix:
  - DIST=ubuntu REL=precise
before_install:
 - tools/travis_chroot prepare
script:
 - export
 - tools/travis_chroot run echo "Success!"
 - tools/travis_chroot run export
 # just a test ;-)
 - tools/travis_chroot run sudo apt-get build-dep python-mvpa2
